liraymond04/bcharity-vms

apps/app/package.json
apps/app/src/components/Dashboard/index.tsx
apps/app/src/components/Sidebar/Sidebar.tsx
apps/app/src/components/Sidebar/TabTile.tsx
apps/app/tailwind.config.js

- add heroicons for icons
- add sidebar size (267px) to tailwind config
- create Sidebar UI components
- add a sidebar to Dashboard page

VM-67: build Sidebar component and dashboard tabs UI

---

apps/app/package.json
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationCauses.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationDashboard.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationHome.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationSettings.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerCauses.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerDashboard.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerHome.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerSettings.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerVHR.tsx
apps/app/src/components/Dashboard/index.tsx
pnpm-lock.yaml

- fix heroicons error
- components/Dashboard/index.tsx now renders a Volunteer dashboard or Organization dashboard
- boilerplate tab components for volunteer dashboard and organization dashboard created

VM-46/82 build dashboard tabs for volunteers and organizations

---

apps/app/src/components/Privacypolicy/index.tsx
apps/app/src/pages/privacypolicy.tsx

I created a new one because I couldn't find my old one

Privacy Policy

---

apps/app/package.json
apps/app/src/components/Dashboard/Modals/Error.tsx
apps/app/src/components/Dashboard/Modals/PublishOpportunityModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/ColumnDefs.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx
apps/app/src/lib/lensClient.ts
apps/app/src/lib/types.ts
apps/app/src/lib/usePostData.ts
pnpm-lock.yaml

- add @lens-protocol/client dependency
- make simple Error component
- modify org vhr grid column defs to match data schema (comment out VHR progress bar for now)
- load vhr data for organizations into grid

VM-71: Organization VHR tab - grid data fetching

---

apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerSettings.tsx
apps/app/src/components/Shared/ThemeButton.tsx

- Added sun and moon icons by the dark mode toggle for better user experience

Added sun and moon icons to dark mode toggle for better user experience

---

apps/app/src/components/Dashboard/VolunteerDashboard/GetBalance.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerVHR.tsx
apps/app/src/pages/_app.tsx

Wagmi now uses the alchemy provider, so an Alchemy API key is required

VM-148: Volunteer VHR tab loading error

---

apps/app/data/verified.ts
apps/app/src/components/Dashboard/Modals/ModifyOpportunityModal.tsx
apps/app/src/components/Dashboard/Modals/PublishOpportunityModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/ColumnDefs.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx
apps/app/src/components/UI/Input.tsx
apps/app/src/components/UserSettingsDashboard/UserDelete.tsx
apps/app/src/components/UserSettingsDashboard/UserDispatcher.tsx
apps/app/src/lib/lens-protocol/getOpportunityMetadata.ts
apps/app/src/lib/types.ts

- create modify cause modal
- change type of `OpportunityMetadata` to not be null and add empty strings as defaults
- in `getOpportunityMetadata.ts` return only the most recent version of posts
- cleanup uses of `checkAuth` around the application

VM-116: Organization causes tab - modify cause modal

---

apps/app/src/components/Shared/Navbar/Login/Create/index.tsx

Fix create profile stuck pending
Fix create profile unhelpful error message

VM-149: create profile error message [object Object]

---

apps/app/src/components/Dashboard/Modals/DeleteOpportunityModal.tsx
apps/app/src/components/Dashboard/Modals/ModifyOpportunityModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx

Create modal for deleting volunteer opportunities

VM-110: Organization VHR tab - delete opportunity modal

---

apps/app/src/components/Dashboard/VolunteerDashboard/BrowseCard.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerCauses.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerHome.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerVHR.tsx
apps/app/src/components/Sidebar/Sidebar.tsx
apps/app/src/lib/search.ts

- fixes bugs VM-163 and VM-160
- reduce code duplication between volunteer dashboard causes and vhr tabs

VM-160 and VM-160

---

apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationDashboard.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/OrganizationLogVHR.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/VHRVerifyCard.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerDashboard.tsx
apps/app/src/lib/lens-protocol/getOpportunityMetadata.ts

- quick fix for getOpportunityMetadata

WIP on VM-64

---

apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/OrganizationLogVHR.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/VHRDetailCard.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/VHRVerifyCard.tsx

- continues off of WIP PR
- finish detail card

VM-64: Organization dashboard - verify hours: build UI components

---

apps/app/src/components/Causes/CauseCard.tsx
apps/app/src/components/Causes/index.tsx
apps/app/src/components/Dashboard/Modals/ModifyCauseModal.tsx
apps/app/src/components/Dashboard/Modals/PublishCauseModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationCauses.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerCauses.tsx

- shows images on cause cards
- also implements new cause card styling

VM-200: Display image on cause cards

---

apps/app/src/components/Dashboard/Modals/ModifyCauseModal.tsx
apps/app/src/components/Dashboard/Modals/ModifyOpportunityModal.tsx
apps/app/src/components/Dashboard/Modals/PublishCauseModal.tsx
apps/app/src/components/Dashboard/Modals/PublishOpportunityModal.tsx
apps/app/src/components/Volunteers/VolunteerCard.tsx
apps/app/src/lib/lens-protocol/getOpportunityMetadata.ts

- avoid parameter mutation in publish/modify modals when attaching imageUrl
- fix getOpportunityMetadata

VM-253: Images not showing up on volunteer cards

---

apps/app/src/components/Home/index.tsx

- adds more x margin to accomodate card growth

VM-252: Hover effect causes card to overflow container on homepage

---

apps/app/src/components/Dashboard/Modals/ModifyOpportunityModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/OrganizationLogVHR.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/VHRDetailCard.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationLogVHR/VHRVerifyCard.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerVHR.tsx
apps/app/src/components/Volunteers/VolunteerCard.tsx
apps/app/src/lib/lens-protocol/createCollect.ts
apps/app/src/lib/lens-protocol/createComment.ts
apps/app/src/lib/lens-protocol/getAttribute.ts
apps/app/src/lib/lens-protocol/getCauseMetadata.ts
apps/app/src/lib/lens-protocol/getOpportunityMetadata.ts
apps/app/src/lib/lens-protocol/getVerifyRequestMetadata.ts
apps/app/src/lib/lens-protocol/useApply.ts
apps/app/src/lib/lens-protocol/usePostData.ts
apps/app/src/lib/lens-protocol/useVHRRequests.ts
apps/app/src/lib/types.ts

- fix getAttribute to return empty string instead of null
- move getAttribute to getAttribute.ts
- write hook to fetch VHR requests for an organization
- write utility to get vhr request metadata

VM-222 & 223: Organization dashboard - verify hours: data fetching and Organization dashboard - verify hours: accept/reject buttons

---

apps/app/src/components/Causes/CausePage.tsx

VM-341 Outline

---

apps/app/src/components/Dashboard/Modals/GoalModal.tsx
apps/app/src/components/Dashboard/Modals/ModifyCauseModal.tsx
apps/app/src/components/Dashboard/Modals/ModifyOpportunityModal.tsx
apps/app/src/components/Dashboard/Modals/PublishCauseModal.tsx
apps/app/src/components/Dashboard/Modals/PublishOpportunityModal.tsx
apps/app/src/components/Dashboard/Modals/VHRGoalModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx

- fixes errors of not owning profile when trying to create post or comment
- creates grid tabs for organization vhr page

VM-262: Organization VHR tab: create grid tabs

---

apps/app/public/locales/en.json
apps/app/public/locales/zh-CN.json
apps/app/src/components/Shared/Navbar/Login/Create/index.tsx
apps/app/src/components/Shared/Navbar/MenuItems.tsx

Add better error handling in create profile

VM:376 - Add create profile button in menu

---

apps/app/package.json
apps/app/src/components/Shared/Footer/index.tsx
apps/app/src/components/Shared/Gradient/GradientWrapper.tsx
apps/app/src/components/Shared/Modal/GradientModal.tsx
apps/app/src/components/Shared/Navbar/Login/Create/index.tsx
apps/app/src/components/Shared/Navbar/Login/Create/namespace.ts
apps/app/src/components/Shared/Navbar/Login/WalletSelector.tsx
apps/app/src/components/Shared/Navbar/Login/index.tsx
apps/app/src/components/Shared/Navbar/Login/namespace.ts
apps/app/src/components/Shared/Navbar/MenuItems.tsx
apps/app/src/components/Shared/Navbar/index.tsx
apps/app/src/components/Shared/Navbar/namespace.ts
apps/app/src/components/Shared/index.ts
apps/app/src/components/index.ts
apps/app/typedoc.json

This PR is mostly to bring the `typedoc.json` and new doc script into the main branch.

Add partial docs of shared components

---

apps/app/src/components/Profile/Organization.tsx
apps/app/src/components/Profile/Volunteer.tsx
apps/app/src/lib/lens-protocol/index.ts
apps/app/src/lib/lens-protocol/useCausesDonatedTo.ts
apps/app/src/lib/lens-protocol/useRegisteredOpportunities.ts
apps/app/src/lib/metadata/PostTags.ts

- fixes layout of top section
- does not implement showing opportunities/causes of a volunteer: waiting on ability to publish applications and unable to get causes a profile has donated to

VM-386: Fix /profile/voluneer/[id] page styling

---

apps/app/public/locales/en.json
apps/app/public/locales/zh-CN.json
apps/app/src/components/Dashboard/Modals/ModifyOpportunityModal.tsx
apps/app/src/components/Dashboard/Modals/PublishOpportunityDraftModal.tsx
apps/app/src/components/Dashboard/Modals/PublishOpportunityModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/ColumnDefs.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx
apps/app/src/components/UI/Input.tsx

Add chinese translation for publish now and registration required
Fix ongoing checkbox editable in delete modal

VM-388: Add publish draft button for opportunities table

---

apps/app/src/lib/lens-protocol/createProfile.ts
apps/app/src/lib/lens-protocol/useApplications.ts
apps/app/src/lib/lens-protocol/useVHRRequests.ts

createProfile needs wallet address argument now. Need to edit the index where it is used

Migrated to Lens v2. createProfile has new address argument.

---

apps/app/src/components/Shared/Navbar/Login/Create/index.tsx
apps/app/src/components/Shared/Navbar/Login/namespace.ts
apps/app/src/components/Shared/Navbar/index.tsx
apps/app/src/components/UserSettingsDashboard/Permissons.tsx
apps/app/src/components/UserSettingsDashboard/UserDashboard.tsx
apps/app/src/components/UserSettingsDashboard/UserDelete.tsx
apps/app/src/components/UserSettingsDashboard/UserDispatcher.tsx
apps/app/src/components/UserSettingsDashboard/UserHome/NFTPicture.tsx
apps/app/src/components/UserSettingsDashboard/UserHome/Picture.tsx
apps/app/src/components/UserSettingsDashboard/UserHome/SelectAvatar.tsx

Updated the above folder components to Lens v2. Missing functionality for NFTpicture and UserDelete. The rendering components have been edited to remove them. Files still there with errors.

Migrated shared/navbar and userSettingDashboard folders to Lens v2

---

apps/app/src/components/Shared/DonateButton.tsx
apps/app/src/components/config.ts

Finished up DonateButton migration

Completion of DonateButton

---

apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationHome.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerCauses.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerHome.tsx
apps/app/src/components/Dashboard/VolunteerDashboard/VolunteerVHR.tsx
apps/app/src/components/Shared/Navbar/Login/index.tsx
apps/app/src/components/UserSettingsDashboard/UserDispatcher.tsx

Functionality of dispatcher fixed and added notifcations for success and errors. I could not replicate the original runtime error in the bug but the unauthenticated error was fixed. Corrected some of the missing displays. Organization one may need to be edited more, need to check on organization account.

Bug fixes for Dispatcher and incorrect displays

---

apps/app/src/components/Profile/Volunteer.tsx
apps/app/src/components/UserSettingsDashboard/UserHome.tsx

Ensure the thirdweb client ID and secret key in the .env.local file is not enclosed in quotations, and also ensure that the secret key is stored in the SECRET_KEY variable for profile updating to work. Slight UI tweaks as well in the profile page.

User Profile Updates

---

apps/app/src/components/Dashboard/Modals/PublishOpportunityDraftModal.tsx
apps/app/src/components/Dashboard/OrganizationDashboard/OrganizationVHR.tsx

"When an opportunity draft post is created then an organization user attempts to publish it, it appears posted on Good-VMS but not in the dashboard."

Fixed filtering issue for "Ongoing" postings
